# Generated by Django 4.2.3 on 2023-07-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_alter_advertisements_table_comment'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='advertisements',
            table_comment=None,
        ),
    ]
