# Generated by Django 4.2.3 on 2023-07-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_alter_advertisements_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='Advertisements',
        ),
    ]
