# Generated by Django 4.2.3 on 2023-07-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_alter_advertisements_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={},
        ),
    ]
