# Generated by Django 4.2.3 on 2023-07-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisements_uuu_alter_advertisements_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='uuu',
        ),
    ]
