# Generated by Django 4.2.3 on 2023-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_remove_advertisements_uuu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
